#!/bin/bash
set -euo pipefail

DOTFILES_REPO="https://github.com/osharko/dotfiles.git"
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/Progetti/dotfiles}"

# ── Clona il repo se non già presente ──
if [ ! -d "$DOTFILES_DIR" ]; then
    echo "▸ Cloning dotfiles..."
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
fi
cd "$DOTFILES_DIR"

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# ── 1. Prerequisiti (paru + chezmoi) ──
if ! command -v paru &>/dev/null; then
    echo "▸ Installing paru..."
    sudo pacman -S --noconfirm paru
fi

if ! command -v chezmoi &>/dev/null; then
    echo "▸ Installing chezmoi..."
    paru -S --noconfirm --needed chezmoi
fi

# ── Configura chezmoi ──
CHEZMOI_CONFIG="$HOME/.config/chezmoi/chezmoi.toml"
if [ ! -f "$CHEZMOI_CONFIG" ]; then
    echo "▸ Configuring chezmoi source dir..."
    mkdir -p "$(dirname "$CHEZMOI_CONFIG")"
    printf 'sourceDir = "%s"\n' "$DOTFILES_DIR" > "$CHEZMOI_CONFIG"
fi

# ── 2. Configura greetd (DMS greeter) ──
echo "▸ Configuring greetd..."
sudo tee /etc/greetd/config.toml > /dev/null << 'EOFGREETD'
[terminal]
vt = 1

[default_session]
command = "/usr/bin/dms-greeter --command niri --cache-dir /var/cache/dms-greeter -C /etc/greetd/niri/config.kdl"
user = "greeter"
EOFGREETD

sudo mkdir -p /etc/greetd/niri

sudo tee /etc/greetd/niri/config.kdl > /dev/null << 'EOFNIRI'
hotkey-overlay {
    skip-at-startup
}

environment {
    DMS_RUN_GREETER "1"
}

gestures {
    hot-corners {
        off
    }
}

layout {
    background-color "#000000"
}

include "/etc/greetd/niri/dms.kdl"
EOFNIRI

sudo tee /etc/greetd/niri/dms.kdl > /dev/null << 'EOFDMS'
input {
    keyboard {
        xkb
        numlock
    }
    touchpad {
        tap
        natural-scroll
    }
    mouse
    trackpoint
}

debug {
    honor-xdg-activation-with-invalid-serial
}
EOFDMS

sudo chown -R root:greeter /etc/greetd/niri
sudo chmod 755 /etc/greetd/niri
sudo chmod 644 /etc/greetd/config.toml /etc/greetd/niri/config.kdl /etc/greetd/niri/dms.kdl
sudo chown root:root /etc/greetd/config.toml
sudo systemctl enable greetd.service

# ── 3. Abilita servizi ──
echo "▸ Enabling services..."
sudo systemctl enable --now sshd.service

# ── 4. Pacchetti ufficiali ──
if command -v pacman &>/dev/null; then
    echo "▸ Installing official packages..."
    xargs -d '\n' sudo pacman -S --noconfirm --needed < "$DOTFILES_DIR/pkglist.txt"
fi

# ── 5. Pacchetti AUR ──
if command -v paru &>/dev/null; then
    echo "▸ Installing AUR packages..."
    xargs -d '\n' paru -S --noconfirm --needed < "$DOTFILES_DIR/foreign-pkglist.txt"
fi

# ── 6. SSH da 1Password ──
ENV_FILE="$DOTFILES_DIR/.env"
[ -f "$ENV_FILE" ] && source "$ENV_FILE"

: "${VAULT:=PersonalConfiguration}"
: "${SSH_ITEM:=Default}"
: "${SSH_CONFIG_DOC:=config}"
: "${SSH_AUTH_KEYS_DOC:=authorized_keys}"
: "${SSH_PRIVATE_KEY_PATH:=$HOME/.ssh/id_ed25519}"
: "${SSH_PUBLIC_KEY_PATH:=$HOME/.ssh/id_ed25519.pub}"
: "${SSH_CONFIG_PATH:=$HOME/.ssh/config}"
: "${SSH_AUTH_KEYS_PATH:=$HOME/.ssh/authorized_keys}"

if [ ! -f "$ENV_FILE" ]; then
    mkdir -p "$(dirname "$ENV_FILE")"
    cat > "$ENV_FILE" <<-EOF
# Generated by bootstrap
VAULT=$VAULT
SSH_ITEM=$SSH_ITEM
SSH_CONFIG_DOC=$SSH_CONFIG_DOC
SSH_AUTH_KEYS_DOC=$SSH_AUTH_KEYS_DOC
SSH_PRIVATE_KEY_PATH=$SSH_PRIVATE_KEY_PATH
SSH_PUBLIC_KEY_PATH=$SSH_PUBLIC_KEY_PATH
SSH_CONFIG_PATH=$SSH_CONFIG_PATH
SSH_AUTH_KEYS_PATH=$SSH_AUTH_KEYS_PATH
EOF
    echo "▸ Created $ENV_FILE with defaults"
fi

if command -v op &>/dev/null; then
    if timeout 5 op whoami --format json &>/dev/null; then
        echo "▸ Exporting SSH keys from 1Password..."
        mkdir -p "$(dirname "$SSH_PRIVATE_KEY_PATH")"

        op item get "$SSH_ITEM" --vault "$VAULT" --fields "chiave privata" --reveal > "$SSH_PRIVATE_KEY_PATH"
        chmod 600 "$SSH_PRIVATE_KEY_PATH"

        op item get "$SSH_ITEM" --vault "$VAULT" --fields "public key" > "$SSH_PUBLIC_KEY_PATH"
        chmod 644 "$SSH_PUBLIC_KEY_PATH"

        op document get "$SSH_CONFIG_DOC" --vault "$VAULT" --force --output "$SSH_CONFIG_PATH"
        chmod 600 "$SSH_CONFIG_PATH"

        op document get "$SSH_AUTH_KEYS_DOC" --vault "$VAULT" --force --output "$SSH_AUTH_KEYS_PATH"
        chmod 644 "$SSH_AUTH_KEYS_PATH"

        echo "✓ SSH keys exported"
    else
        echo "⚠ 1Password not logged in. You can:"
        echo "   1. Set OP_SERVICE_ACCOUNT_TOKEN in $ENV_FILE, or"
        echo "   2. Run 'op signin' then re-run: cd \"$DOTFILES_DIR\" && ./bootstrap.sh"
        read -r -p "   Try 'op signin' now? [y/N] " REPLY
        if [[ "$REPLY" =~ ^[Yy]$ ]]; then
            op signin
            if timeout 5 op whoami --format json &>/dev/null; then
                echo "▸ Signed in, re-running bootstrap..."
                exec ./bootstrap.sh
            fi
        fi
    fi
else
    echo "⚠ 1Password CLI not found — install 1password-cli (AUR) and re-run"
fi

# ── 7. Applica dotfiles con chezmoi ──
echo "▸ Applying dotfiles..."
chezmoi apply

echo "✓ Bootstrap complete — reboot recommended"
